name: Auto Assign to Project

on:
  issues:
    types: [opened]

jobs:
  assign-to-project:
    runs-on: ubuntu-latest
    steps:
    - name: Assign to Project
      uses: srggrs/assign-one-project-github-action@1.3.1
      with:
        project: 'Token Listings'
        status: 'Todo'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
